config/routes.rb
Rails.application.routes.draw do
  resources :memberdetails do
    collection do
      get :download
    end
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :emails
  get 'ps/ps4'

  get 'ps/ps5'

  authenticated :user do

      root 'userpersnaldets#new'

    end
get 'home/home'
  get 'memberdetails/download'
  root 'home#home'
  resources :mdos
  resources :maa_addresses
  resources :regs
  resources :userpersnaldets
  captcha_route


  #root 'messages#index'
  resources :messages, only: [:create, :destroy, :index, :new]
  resources :programs do
    resources :comts

  end

  #resources :media_contents, only: [:create]

  delete 'delete_media', to: "media_contents#delete_media"
  delete 'delete_all', to: 'media_contents#delete_all'
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'usersinfo/userlist'
 #root 'programs#index'
  authenticated :user do
    #root 'programs#index'
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end
   #root 'courses#index'
  get 'courses/show'
  resources :courses do
    member do
      get 'upload', to: 'courses#upload'
      patch 'upload', to: 'courses#do_upload'
      get 'resume_upload', to: 'courses#resume_upload'
      patch 'update_status', to: 'courses#update_status'
      get 'reset_upload', to: 'courses#reset_upload'
    end
  end

  match ':controller(/:action(/:id))', :via => [:get,:patch,:post]
  get 'usersinfo/User'

  get 'usersinfo/uerlist'

  get 'usersinfo/userstat'

  #get 'usersinfo/show' => 'usersinfo/userlist'


  #root 'usersinfo#userstat'
  resources :usersinfo
  resources :project


  #root 'usersinfo#userlist'
  #get 'usersinfo/ban'
  #get 'usersinfo/unban'
  post "/regs/:id" => "regs#show"
  post "/hook" => "regs#hook"
  post "/mdos/:id" => "mdos#show"
  post "/hook" => "mdos#hook"
  get "myprofile" => "application#profile", :as => :myprofile

  get 'project/home'
 #root 'project#home'
  #root 'regs#index'
 #root 'mdos#index'

  #root 'userpersnaldets#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/memberdetail.rb
require 'csv'
class Memberdetail < ApplicationRecord
  #has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
   has_attached_file :image, styles: { medium: "300x300>", :thumb => "100x100#",
                                       :small  => "150x150>",
                                       :medium => "200x200"  }
   has_attached_file :proof, styles: { medium: "300x300>", :thumb => "100x100#",
                                       :small  => "150x150>",
                                       :medium => "200x200"  }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
   def self.to_csv(options = {})
     desired_columns = ["id", "fullname", "fathername", "phnumber",'bloodgroup','image']
     CSV.generate(options) do |csv|
       csv << desired_columns
       all.each do |donate|
         csv << donate.attributes.values_at(*desired_columns)
       end
     end
   end
end

app/controllers/memberdetails_controller.rb
class MemberdetailsController < ApplicationController
  before_action :set_memberdetail, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /memberdetails
  # GET /memberdetails.json
  def index
    #@memberdetails = Memberdetail.all
    @memberdetails = Memberdetail.paginate(:page => params[:page], :per_page => 5)
    respond_to do |format|
      format.html
      format.csv { send_data @memberdetails.to_csv }
      format.xls
    end
  end

  # GET /memberdetails/1
  # GET /memberdetails/1.json
  def show

  end

  # GET /memberdetails/new
  def new
    @memberdetail = Memberdetail.new
  end

  # GET /memberdetails/1/edit
  def edit
  end

  # POST /memberdetails
  # POST /memberdetails.json
  def create
    @memberdetail = Memberdetail.new(memberdetail_params)

    respond_to do |format|
      if @memberdetail.save
        format.html { redirect_to memberdetails_path, notice: 'Memberdetail was successfully created.' }
        #format.json { render :show, status: :created, location: @memberdetail }
      else
        format.html { render :new }
        format.json { render json: @memberdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberdetails/1
  # PATCH/PUT /memberdetails/1.json
  def update
    respond_to do |format|
      if @memberdetail.update(memberdetail_params)
        format.html { redirect_to @memberdetail, notice: 'Memberdetail was successfully updated.' }
        format.json { render :show, status: :ok, location: @memberdetail }
      else
        format.html { render :edit }
        format.json { render json: @memberdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberdetails/1
  # DELETE /memberdetails/1.json
  def destroy
    @memberdetail.destroy
    respond_to do |format|
      format.html { redirect_to memberdetails_url, notice: 'Memberdetail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def download
    @entries = 'public/Pics.sh.txt'
    send_file @entries,
              :type => 'text/text; charset=UTF-8;',
              :disposition => "attachment; filename=Pics.sh.txt"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memberdetail
      @memberdetail = Memberdetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def memberdetail_params
      params.require(:memberdetail).permit(:fullname, :fathername, :phnumber, :bloodgroup, :image,:proof,:email)
    end
end

app/helpers/memberdetails_helper.rb
module MemberdetailsHelper
end

app/views/memberdetails/_form.html.erb
<div class="container">
  <div class="row main">
    <div class="main-login main-center">
      <h5>Enter your details for ID card</h5>
      <%= form_for @memberdetail, html: { multipart: true } do |f| %>

        <div class="form-group">
          <label for="name" class="cols-sm-2 control-label">Your Name</label>
          <div class="cols-sm-10">
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
              <!--<input type="text" class="form-control" name="name" id="name"  placeholder="Enter your Name"/>-->
              <%= f.text_field :fullname,class:"form-control"  , placeholder:"Enter your Full Name" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <label for="fullname" class="cols-sm-2 control-label">Father Name</label>
          <div class="cols-sm-10">
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
              <!--<input type="text" class="form-control" name="email" id="email"  placeholder="Enter your father name"/>-->
              <%= f.text_field :fathername,class:"form-control"  , placeholder:"Enter your Father Name" %>

            </div>
          </div>
        </div>

        <div class="form-group">
          <label for="username" class="cols-sm-2 control-label">Contact Number</label>
          <div class="cols-sm-10">
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-users fa" aria-hidden="true"></i></span>
              <!--<input type="text" class="form-control" name="username" id="username"  placeholder="Enter your Username"/>-->
              <%= f.text_field :phnumber,class:"form-control" , placeholder:"Enter mobile number with country code" %>
              <%#= f.text_field :phnumber, class: 'form-control', autofocus: true, placeholder: 'xxx-xxx-xxxx', value: number_to_phone(@my_variable.telephone, area_code: true, extension: 555) %>
            </div>
          </div>
        </div>

          <div class="form-group">
            <label for="username" class="cols-sm-2 control-label">Email</label>
            <div class="cols-sm-10">
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon1"><i class="fa fa-envelope-o fa-fw" aria-hidden="true"></i></span></span>
                <!--<input type="text" class="form-control" name="username" id="username"  placeholder="Enter your Username"/>-->
                <%= f.email_field :email,class:"form-control" , placeholder:"Enter your email id" %>
                <%#= f.text_field :phnumber, class: 'form-control', autofocus: true, placeholder: 'xxx-xxx-xxxx', value: number_to_phone(@my_variable.telephone, area_code: true, extension: 555) %>
              </div>
            </div>
          </div>

        <div class="form-group">
          <label for="password" class="cols-sm-2 control-label">Blood group</label>
          <div class="cols-sm-10">
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
              <!--<input type="password" class="form-control" name="password" id="password"  placeholder="Enter your Password"/>-->
              <div id="two_select">
              <%#= f.select  :bloodgroup ,options_from_collection_for_select(@people, "id", "name")  %>
                <%#= f.select(:bloodgroup) %>
                <%#= select(:bloodgroup, [['Lisbon', 1], ['Madrid', 2]]) %>
                <%= f.select :bloodgroup, [["Select Blood group", "nil"],
                                           [ "A RhD positive (A+)", "A+"],
                                           [ "A RhD negative (A-)", "A-"],
                                           ["B RhD positive (B+)",  "B+"],
                                           ["B RhD negative (B-)",  "B-"],
                                           ["O RhD positive (O+)",  "O+"],
                                           ["O RhD negative (O-)",  "O-"],
                                           ["AB RhD positive (AB+)","AB+"],
                                           ["AB RhD negative (AB-)","AB-"]], {}, { 'data-width' => "100%", :class => "selectpicker", id: 'sel'} %>

                <!--<select class="selectpicker" data-width="100px"   style="background-color: black;font-size: 250%"  onchange="validate_select()" data-live-search="true" id="dropone" size="1">-->
                    <!--<option value="" style="font-size: 150%">Select Blood group</option>-->
                    <!--<option value="a" style="font-size: 150%">A RhD positive (A+)</option>-->
                    <!--<option value="b" style="font-size: 150%">A RhD negative (A-)</option>-->
                    <!--<option value="c" style="font-size: 150%">B RhD positive (B+)</option>-->
                    <!--<option value="c" style="font-size: 150%">B RhD negative (B-)</option>-->
                    <!--<option value="c" style="font-size: 150%">O RhD positive (O+)</option>-->
                    <!--<option value="c" style="font-size: 150%">O RhD negative (O-)</option>-->
                    <!--<option value="c" style="font-size: 150%">AB RhD positive (AB+)</option>-->
                    <!--<option value="c" style="font-size: 150%">AB RhD negative (AB-)</option>-->
                  <!--</select>-->

                <script>
                  $('.selectpicker').selectpicker({
                    style: 'btn-info',
                    size: 5
                  });
                </script>
                <br>
              </div>

            </div>
          </div>
        </div>
          <p>
            <%= f.label 'Insert Latest Image'%>
            <%= f.file_field :image,label: 'Upload Attachment',class:"btn btn-small btn-primary btn-inverse" %>
          </p>
          <p>
            <%= f.label 'Insert ID Proof'%>
            <%= f.file_field :proof,label: 'Upload Attachment',class:"btn btn-small btn-primary btn-inverse" %>
          </p>

        <div class="form-group ">
          <!--<a href="http://deepak646.blogspot.in" target="_blank" type="button" id="button" class="btn btn-primary btn-lg btn-block login-button">Register</a>-->
          <%= f.button :submit , class:"btn btn-primary btn-lg btn-block login-button", id: 'register' %>
        </div>

      <% end %>
    </div>
  </div>
</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->


<style>
  /*
/* Created by Filipe Pina
 * Specific styles of signin, register, component
 */
  /*
   * General styles
   */
  #playground-container {
    height: 500px;
    overflow: hidden !important;
    -webkit-overflow-scrolling: touch;
  }
  body, html{

    font-family: 'Oxygen', sans-serif;
    background-size: cover;
  }

  .main{
    margin:50px 15px;
  }

  h1.title {
    font-size: 50px;
    font-family: 'Passion One', cursive;
    font-weight: 400;
  }

  hr{
    width: 10%;
    color: #fff;
  }

  .form-group{
    margin-bottom: 15px;
  }

  label{
    margin-bottom: 15px;
  }

  input,
  input::-webkit-input-placeholder {
    font-size: 11px;
    padding-top: 3px;
  }

  .main-login{
    background-color: #fff;
    /* shadows and rounded borders */
    -moz-border-radius: 2px;
    -webkit-border-radius: 2px;
    border-radius: 2px;
    -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);

  }
  .form-control {
    height: auto!important;
    padding: 8px 12px !important;
  }
  .input-group {
    -webkit-box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.21)!important;
    -moz-box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.21)!important;
    box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.21)!important;
  }
  #button {
    border: 1px solid #ccc;
    margin-top: 28px;
    padding: 6px 12px;
    color: #666;
    text-shadow: 0 1px #fff;
    cursor: pointer;
    -moz-border-radius: 3px 3px;
    -webkit-border-radius: 3px 3px;
    border-radius: 3px 3px;
    -moz-box-shadow: 0 1px #fff inset, 0 1px #ddd;
    -webkit-box-shadow: 0 1px #fff inset, 0 1px #ddd;
    box-shadow: 0 1px #fff inset, 0 1px #ddd;
    background: #f5f5f5;
    background: -moz-linear-gradient(top, #f5f5f5 0%, #eeeeee 100%);
    background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #f5f5f5), color-stop(100%, #eeeeee));
    background: -webkit-linear-gradient(top, #f5f5f5 0%, #eeeeee 100%);
    background: -o-linear-gradient(top, #f5f5f5 0%, #eeeeee 100%);
    background: -ms-linear-gradient(top, #f5f5f5 0%, #eeeeee 100%);
    background: linear-gradient(top, #f5f5f5 0%, #eeeeee 100%);
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#f5f5f5', endColorstr='#eeeeee', GradientType=0);
  }
  .main-center{
    margin-top: 30px;
    margin: 0 auto;
    max-width: 400px;
    padding: 10px 40px;
    background:#009edf;
    color: #FFF;
    text-shadow: none;
    -webkit-box-shadow: 0px 3px 5px 0px rgba(0,0,0,0.31);
    -moz-box-shadow: 0px 3px 5px 0px rgba(0,0,0,0.31);
    box-shadow: 0px 3px 5px 0px rgba(0,0,0,0.31);

  }
  span.input-group-addon i {
    color: #009edf;
    font-size: 17px;
  }

  .login-button{
    margin-top: 5px;
  }

  .login-register{
    font-size: 11px;
    text-align: center;
  }
  button.btn.dropdown-toggle.bs-placeholder.btn-info {
    width: 7.5cm;

  }
  span.text {
    color: black;
    font-size: smaller;
    width: 6.4cm;

  }
</style>
<script>
  $(document).ready(function() {
    $('.selectpicker').selectpicker();
  });

</script>

<script>
  var $input = $('input:text'),
      $register = $('#register');

  $register.attr('disabled', true);
  $input.keyup(function() {
    var trigger = false;
    $input.each(function() {
      if (!$(this).val()) {
        trigger = true;
      }
    });
    trigger ? $register.attr('disabled', true) : $register.removeAttr('disabled');
  });
</script>

app/views/memberdetails/edit.html.erb
<h1>Editing Memberdetail</h1>

<%= render 'form', memberdetail: @memberdetail %>

<%= link_to 'Show', @memberdetail %> |
<%= link_to 'Back', memberdetails_path %>

app/views/memberdetails/index.html.erb
<h1 align="center" style="color: #B00100">Member details for Photo ID</h1>

<div style="">
  <div style="float: left; position: fixed;width: 330px;margin-left: 11%">  <%= will_paginate @memberdetails, renderer: BootstrapPagination::Rails,:previous_label => 'Previous', :next_label => 'Next' %>
  </div>
  <div style=""><%= link_to new_memberdetail_path do %>
        <h1 align="center">Click here to Add New Member</h1>
    <% end %>
  </div>
  <div style=" width: 450px;margin-left: 10%;margin-bottom: -2%;border: double;" id="dicc">
   <p><b style="color: red;font-size: large">Note: </b><i style="color: green;font-weight: bold">Please contact us via email or message on website for public key to <b style="color: blue">Download all pics</b>
      <br>This is bash file unless u get public key u cannot access pics</i></p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <span class="glyphicon glyphicon-arrow-down" aria-hidden="true" style='background: #222;color: #fff;display: inline-block;margin: 10px 10px 0 0;padding: 5px 10px'></span>
  </div>
  <div style="float: left; width: 10px;">
    <div class="row">

    <%= button_to "Export To Excel ?", memberdetails_path(format: "xls"),method: :get, id: 'triangle-righ',class:"btn-change7" %>
    <%= button_to "Download all pics ?",download_memberdetails_path,:file_name => "public/Pics.sh.txt",method: :get, id: 'triangle-right',class:"btn-change7" %>

    </div> </div>

  <br style="clear: left;" />
</div>


<div class="container" >
</div>

</table>
<div class="container">
  <div class="row">
    <div class="table-responsive">
      <table class="table table-hover" style="background-color: white; border: double">
        <thead>
        <tr>
          <th>S:No</th>
          <th>Full Name</th>
          <th>Fathername</th>
          <th>Phnumber</th>
          <th colspan="2">Email</th>
          <th>Bloodgroup</th>
          <th>Photo</th>
          <th>ID Proof</th>
          <th>Edit</th>
          <!--<th>Delete</th>-->
        </tr>
        </thead>
        <tbody id="myTable">
        <% i = 1 %>
        <% @memberdetails.reverse_order.each do |memberdetail| %>
        <tr>
          <td><%= i %></td>
          <td><%= memberdetail.fullname %></td>
          <td><%= memberdetail.fathername %></td>
          <td><%= memberdetail.phnumber %></td>
          <td colspan="2"><%= memberdetail.email %></td>
          <td><%= memberdetail.bloodgroup %></td>
          <a href="" data-toggle="modal" data-target="#modal-<%= memberdetail.id %>">
            <td><%= image_tag memberdetail.image.url(:original),class:"img-responsive",id:memberdetail.id %>
            </td>
            <%#= image_tag memberdetail.proof.url(:original),class:"img-responsive",id:memberdetail.id,width:"300" ,height:"200" %>

          </a>

            <%#= image_tag memberdetail.image.url(:original),class:"img-responsive",id:memberdetail.id,width:"300" ,height:"200" %>
            <td>
              <%=link_to image_tag(memberdetail.proof.url(:medium)), memberdetail.proof.url(:original), :popup=>['original_image', 'height=700,width=900'],style: 'background: transparent'%>
            </td>

          <div id="myModal" class="modal">
            <span type="button" class="btn btn-warning btn-lg" data-dismiss="modal" style="margin-left: 75%;margin-top: -1%;color: white"><span class="glyphicon glyphicon-remove" ></span></span>
            <img class="modal-content" id="img01" >
            <div id="caption"> </div>
          </div>


            <script>
              // Get the modal
              var modal = document.getElementById('myModal');

              // Get the image and insert it inside the modal - use its "alt" text as a caption
              var img = document.getElementById('<%= memberdetail.id %>');
              var modalImg = document.getElementById("img01");
              var captionText = document.getElementById("caption");
              img.onclick = function(){
                modal.style.display = "block";
                modalImg.src = this.src;
                captionText.innerHTML = this.alt;
              }

              // Get the <span> element that closes the modal
              var span = document.getElementsByClassName("modal")[0];

              // When the user clicks on <span> (x), close the modal
              span.onclick = function() {
                modal.style.display = "none";
              }
            </script>




          <td><%= link_to 'Edit', edit_memberdetail_path(memberdetail) %></td>
          <!--<td><%#= link_to 'Destroy', memberdetail, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
        </tr>
        <% i += 1 %>
        <% end %>
        </tbody>
      </table>
    </div>

  </div>

</div>
<style>
  table {
    border-collapse: collapse;
    width: 100%;
    text-align: center;
    background-color: whitesmoke;
    vertical-align:middle;

  }

  th, td {

    padding: 8px;
    margin-left: auto;
    margin-right: auto;

    text-align: center;
    border: 2px dashed #f69c55;
  }
  td {text-align:center; vertical-align:middle;}
  tr:nth-child(even){background-color: lightgrey}

  th {
    background-color: darkgreen;
    color: white;
  }
  table, th, td {
    border: 1px solid black;
  }
  tr:hover{background-color:green}


  .btn-change7{
position: relative;
    height: 50px;
    width: 150px;
    background: lightseagreen;
    border:0px;
    color:#fff;
    box-shadow: 0 0 1px #ccc;
    -webkit-transition-duration: 0.7s;
    -webkit-transition-timing-function: linear;
    box-shadow:0px 0 0 #31708f  inset;
  }
  .btn-change7:hover{
    box-shadow:150px 0 0 #31708f inset;
  }


  table#t01 ,tr#t01, td#t01 {
    border: transparent;
  }
  input#triangle-right {
    margin-left: 460%;
    margin-top: -125%;
  }
  input#triangle-righ {
    margin-left: 840%;
    margin-top: 100%;
  }
</style>
<style>
  #myImg {
    border-radius: 5px;
    cursor: pointer;
    transition: 0.3s;
  }

  #myImg:hover {opacity: 0.7;}

  /* The Modal (background) */
  .modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.9); /* Black w/ opacity */
  }

  /* Modal Content (image) */
  .modal-content {
    margin: auto;
    display: block;
    width: 30%;
    max-width: 700px;
  }

  /* Caption of Modal Image */
  #caption {
    margin: auto;
    display: block;
    width: 80%;
    max-width: 700px;
    text-align: center;
    color: #ccc;
    padding: 10px 0;
    height: 150px;
  }

  /* Add Animation */
  .modal-content, #caption {
    -webkit-animation-name: zoom;
    -webkit-animation-duration: 0.6s;
    animation-name: zoom;
    animation-duration: 0.6s;
  }

  @-webkit-keyframes zoom {
    from {-webkit-transform:scale(0)}
    to {-webkit-transform:scale(1)}
  }

  @keyframes zoom {
    from {transform:scale(0)}
    to {transform:scale(1)}
  }

  /* The Close Button */
  .close {
    position: absolute;
    top: 20px;
    right: 2%;
    color: greenyellow;
    font-size: 40px;
    font-weight: bold;
    transition: 0.3s;
  }

  .close:hover,
  .close:focus {
    color: #bbb;
    text-decoration: none;
    cursor: pointer;
  }

  #dicc:hover{
    content: 'ADD';
    color: white;
    background: skyblue;
    text-decoration-color: white;
      }
  #dicc:hover { color: black; cursor: pointer;}

  /* 100% Image Width on Smaller Screens */
  @media only screen and (max-width: 600px){
    .modal-content {
      width: 100%;
    }
  }
</style>

app/views/memberdetails/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table style="background-color: snow;background: border-box">
      <Row style="background: green">
        <Cell style = 'color: white'><Data ss:Type="String">S:No</Data></Cell>
        <Cell style = 'color: white'><Data ss:Type="String">Full Name</Data></Cell>
        <Cell style = 'color: white'><Data ss:Type="String">Father Name</Data></Cell>
        <Cell style = 'color: white'><Data ss:Type="String">Phone Number</Data></Cell>
        <Cell style = 'color: white'><Data ss:Type="String">Blood group</Data></Cell>
        <Cell style = 'color: white'><Data ss:Type="String">Photo</Data></Cell>
      </Row>
      <% i = 1 %>
      <% @memberdetails.each do |memberdetail| %>
          <Row>
            <Cell><Data ss:Type="Number"><%= i %></Data></Cell>
            <Cell><Data ss:Type="String"><%= memberdetail.fullname  %></Data></Cell>
            <Cell><Data ss:Type="String"><%= memberdetail.fathername%></Data></Cell>
            <Cell><Data ss:Type="String"><%=  memberdetail.phnumber%></Data></Cell>
            <Cell><Data ss:Type="String"><%= memberdetail.bloodgroup %></Data></Cell>
            <Cell><Data ss:Type="String"><%= image_tag memberdetail.image.url(:small) %></Data></Cell>
            <% i += 1 %>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/memberdetails/new.html.erb
<h1 align="center">Add your details to get ID card</h1>

<%= render 'form', memberdetail: @memberdetail %>

<%= link_to 'Back', memberdetails_path %>

app/views/memberdetails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fullname:</strong>
  <%= @memberdetail.fullname %>
</p>

<p>
  <strong>Fathername:</strong>
  <%= @memberdetail.fathername %>
</p>

<p>
  <strong>Phnumber:</strong>
  <%= @memberdetail.phnumber %>
</p>

<p>
  <strong>Bloodgroup:</strong>
  <%= @memberdetail.bloodgroup %>
</p>

<p>
  <strong>Recent Image</strong>
  <%= link_to (image_tag @memberdetail.image.url(:small),
                         :border => 0), @memberdetail.image.url %>
</p>
<p>
  <strong>Recent Image</strong>
  <%= link_to (image_tag @memberdetail.proof.url(:small),
                         :border => 0), @memberdetail.proof.url %>
</p>

<%= link_to 'Edit', edit_memberdetail_path(@memberdetail) %> |
<%= link_to 'Back', memberdetails_path %>