config/routes.rb
Rails.application.routes.draw do
  resources :memberdetails do
    collection do
      get :download
    end
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :emails
  get 'ps/ps4'

  get 'ps/ps5'

  authenticated :user do

      root 'userpersnaldets#new'

    end
get 'home/home'
  get 'memberdetails/download'
  root 'home#home'
  resources :mdos
  resources :maa_addresses
  resources :regs
  resources :userpersnaldets
  captcha_route


  #root 'messages#index'
  resources :messages, only: [:create, :destroy, :index, :new]
  resources :programs do
    resources :comts

  end

  #resources :media_contents, only: [:create]

  delete 'delete_media', to: "media_contents#delete_media"
  delete 'delete_all', to: 'media_contents#delete_all'
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'usersinfo/userlist'
 #root 'programs#index'
  authenticated :user do
    #root 'programs#index'
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end
   #root 'courses#index'
  get 'courses/show'
  resources :courses do
    member do
      get 'upload', to: 'courses#upload'
      patch 'upload', to: 'courses#do_upload'
      get 'resume_upload', to: 'courses#resume_upload'
      patch 'update_status', to: 'courses#update_status'
      get 'reset_upload', to: 'courses#reset_upload'
    end
  end

  match ':controller(/:action(/:id))', :via => [:get,:patch,:post]
  get 'usersinfo/User'

  get 'usersinfo/uerlist'

  get 'usersinfo/userstat'

  #get 'usersinfo/show' => 'usersinfo/userlist'


  #root 'usersinfo#userstat'
  resources :usersinfo
  resources :project


  #root 'usersinfo#userlist'
  #get 'usersinfo/ban'
  #get 'usersinfo/unban'
  post "/regs/:id" => "regs#show"
  post "/hook" => "regs#hook"
  post "/mdos/:id" => "mdos#show"
  post "/hook" => "mdos#hook"
  get "myprofile" => "application#profile", :as => :myprofile

  get 'project/home'
 #root 'project#home'
  #root 'regs#index'
 #root 'mdos#index'

  #root 'userpersnaldets#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/program.rb
class Program < ApplicationRecord
  validates :Event_Name,:event_details, presence: true
  #mount_uploader :file_name, MediaUploader
  has_many :comts
  belongs_to :user
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_filter :check_role ,except: :index
  def check_role
    if user_signed_in? && current_user.role_id ==nil

      redirect_to new_reg_path

    end
  end
  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
    @programs = Program.paginate(:page => params[:page], :per_page => 30)
    #@zap = current_user.id
    #@success = CardTransaction.find(1)
  end


  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @user= current_user
    @program = @user.programs.new(program_params)

    respond_to do |format|
      if @program.save
        ProgramMailer.program_created(current_user,@program.Event_Name).deliver
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_program
    @program = Program.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def program_params
    params.require(:program).permit(:Event_Name,:event_details,:photo)

  end
  protected
  def profile
    @account = current_account
  end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= form_for(program) do |f| %>
  <% if program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Event_Name %>
    <%= f.text_field :Event_Name %>
  </div>
    <div class="field">
      <%= f.label :Event_Details %>
      <%= f.text_area :event_details %>
    </div>
    <p>
      <%= f.file_field :photo %>
    </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programs/_in.html.erb
<style>
  .post_container {
  display: inline-block;
  }



</style>
  <section id="gallery" class="parallax section" style="background-image: url(http://themepush.com/demo/runcharity/assets/img/2.jpg);">
    <div class="wrapsection">
      <div class="parallax-overlay" style="background-color:#00c1c1;opacity:0.9;"></div>
      <div class="container">
        <div class="row">
          <div class="col-md-12 sol-sm-12">
            <div class="maintitle">
              <h3 class="section-title">Events Gallery</h3>
              <p class="lead wow flipInX" style="content: '\007C\00a0\00a0';">
                Have a look at your past events gallery, see how much fun we have while helping people all over the world. Join our community today!
              </p>
            </div>
          </div>
          <div class="col-md-11" style="content: '\007C\00a0\00a0';align-content: center">
  <%@programs = Program.all  %>
  <%i = 1  %>
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev" style="float: left">
              <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <table>
              <thead><tr>
                <ul>
                  <div class="col-md-11">

  <% @programs.each do |program| %>
      <%i = 1  %>

                    <div id="myCarouselWrapper" class="container-fluid" style="align-content: center">

                      <div id="myCarousel" class="carousel slide">

                        <div class="carousel-inner" role="listbox">
                          <div class="item active">

                            &nbsp;&nbsp;&nbsp;&nbsp;
                    <th width="1cm" colspan="2"><td>
                <div class="post_container" style="height: 15cm;width: 8cm">
                  <!--<a href="https://ununsplash.imgix.net/photo-1429277158984-614d155e0017?fit=crop&amp;fm=jpg&amp;h=700&amp;q=75&amp;w=1050" title="">-->
                  <%= image_tag program.photo.url(:medium),style:"border: double;display: inline-block; width: 400.2px;height:200px" ,class:"image-responsive"%>
                  <!--<img src="https://ununsplash.imgix.net/photo-1429277158984-614d155e0017?fit=crop&amp;fm=jpg&amp;h=700&amp;q=75&amp;w=1050" alt="" class="image-responsive">-->
                  <div class="description" style="height: 3cm">
                    <b><%= link_to program.Event_Name, program,:id=> 'program.id',style:'background-color: white;height:0.7cm' %></b>
                    <span><i><b><%= link_to 'Donate', mdos_path,style:'background-color: white;height:0.7cm;float:right' %></b></i></span>
                    <span class="camera"><i class="fa fa-camera"></i></span>
                    <div class="clearfix"></div>
                  </div>
                </div>
                          </td>
                             </th> <!-- Controls -->




                          </div>

                        </div>

                      </div>
                    </div>
                    &nbsp;&nbsp;&nbsp;
<% end %>
                    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next" style="float: right">
                      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true" style="float: right"></span>
                      <span class="sr-only">Next</span>
                    </a>
      </div>
                </ul></tr></thead>
            </table> </div>

        </div>
      </div>
    </div>
 </section>
<br>
<% if user_signed_in?  %><%= button_to( "Add New Event", new_program_path, :method => :get )%><% end %>

<% if user_signed_in? && current_user.email == 'st118173@ait.asia' %><%= button_to( "Users Profile", usersinfo_userlist_path, :method => :get )%><%end%>
<% if user_signed_in? && current_user.email != 'st118173@ait.asia' %><%= button_to( "Users list", usersinfo_userlist_path, :method => :get )%><%end%>


         <!--.container-->
<script>
  $('#myCarousel').carousel({
    interval: 4000
  });

  $('.carousel .item').each(function(){
    var next = $(this).next();
    if (!next.length) {
      next = $(this).siblings(':first');
    }
    next.children(':first-child').clone().appendTo($(this));

    for (var i=0;i<2;i++) {
      next=next.next();
      if (!next.length) {
        next = $(this).siblings(':first');
      }

      next.children(':first-child').clone().appendTo($(this));
    }
  });
</script>
<style>

</style>

app/views/programs/_sho.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event name:</strong>
  <%= Program.Event_Name %>
</p>
<p>
  <strong>Event Details:</strong>
  <%= @program.event_details %>
</p>

<h3>Comments</h3>

<%= render @program.comts %>





<p><%= render 'comts/form' %></p>

<%= button_to( "Donate", new_reg_path, :method => :get, :class => 'btn btn-primary' )%>
<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', programs_path %>

app/views/programs/edit.html.erb
<h1>Editing an Event</h1>

<%= render 'form', program: @program %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<% if user_signed_in? && current_user.role==nil %>
<h1>Please Proceed to Pay to get access to webiste</h1>
    <script type="text/javascript">
      window.location.href="/regs/new"  // put your correct path in a string here
    </script>

<% else %>
    <div class="row">
      <div class="col-sm-12 text-center">
        <!--<button id="btnSearch" class="btn btn-primary btn-md center-block" Style="width: 100px;" OnClick="btnSearch_Click" >button</button>-->
        <!--<button id="btnClear" class="btn btn-danger btn-md center-block" Style="width: 100px;" OnClick="btnClear_Click" >button</button>-->

        <% if user_signed_in?  %>
            <%= link_to( new_program_path, :method => :get ,class:"btn btn-info btn-md center-block",id:"btnSearch1" ) do%>
                Add New Event<span class="glyphicon glyphicon-chevron-right"></span>
                <% end %><% end %>

        <% if user_signed_in? && current_user.email == 'st118173@ait.asia' %>
            <%= link_to(  usersinfo_userlist_path, :method => :get,class:"btn btn-danger btn-md center-block",id:"btnSearch2"  ) do%>
                Users Profile <span class="glyphicon glyphicon-chevron-right"></span>
            <%end%> <%end%>
        <% if user_signed_in? && current_user.email != 'st118173@ait.asia' %>
            <%= link_to(  usersinfo_userlist_path, :method => :get,class:"btn btn-success btn-md center-block",id:"btnSearch3"  ) do%>
                Users list<span class="glyphicon glyphicon-chevron-right"></span>
            <%end%> <%end%>
        <% if user_signed_in? && current_user.email = 'st118173@ait.asia' %>
            <%= link_to(  memberdetails_path, :method => :get,class:"btn btn-warning btn-md center-block",id:"btnSearch4") do%>
                Show ID Card Details<span class="glyphicon glyphicon-chevron-right"></span>
            <%end%> <%end%>
      </div>
    </div>
    <div class="col-md-5" style="margin-left: 29%" >

<% end %>
</div>
<br><br>
<!-- Page Content -->
<span style="border: darkolivegreen">

<div class="container" style="background-color: darkseagreen">

  <!-- Page Heading -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Events Conducted
        <small>by MAC</small>
      </h1>
    </div>
  </div>
  <!-- /.row -->
  <% @programs.each do |program| %><br><br><br><br><br >
  <!-- Project One -->
  <div class="row">
    <div class="col-md-7">
<a href="#" data-toggle="modal" data-target="#modal-<%= program.id %>">
          <%= image_tag program.photo.url(:medium),class:"img-responsive",id:program.id,width:"300" ,height:"200" %>

</a>
<%#=link_to image_tag(program.photo.url(:medium)), program.photo.url(:original), :popup=>['original_image', 'height=700,width=900'],style: 'background: transparent'%>
      <div id="myModal" class="modal">
  <span type="button" class="btn btn-warning btn-lg" data-dismiss="modal" style="margin-left: 75%;margin-top: -1%;color: white"><span class="glyphicon glyphicon-remove" ></span></span>
  <img class="modal-content" id="img01">
  <div id="caption"> </div>

</div>

<script>
  // Get the modal
  var modal = document.getElementById('myModal');

  // Get the image and insert it inside the modal - use its "alt" text as a caption
  var img = document.getElementById('<%= program.id %>');
  var modalImg = document.getElementById("img01");
  var captionText = document.getElementById("caption");
  img.onclick = function(){
    modal.style.display = "block";
    modalImg.src = this.src;
    captionText.innerHTML = this.alt;
  }

  // Get the <span> element that closes the modal
  var span = document.getElementsByClassName("modal")[0];

  // When the user clicks on <span> (x), close the modal
  span.onclick = function() {
    modal.style.display = "none";
  }
</script>

    </div>
    <div class="col-md-5" style="" >
      <h3><%= program.Event_Name %></h3>
      <h4>Details</h4>
      <p><%= program.event_details %></p>
      <!--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium veniam exercitationem expedita laborum at voluptate. Labore, voluptates totam at aut nemo deserunt rem magni pariatur quos perspiciatis atque eveniet unde.</p>-->
      <a class="btn btn-success" href="/mdos/new">Donate <span class="glyphicon glyphicon-chevron-right"></span></a>

      <% if user_signed_in? %> <td><%= link_to  edit_program_path(program),class:"btn btn-primary" do %>
          Edit<span class="glyphicon glyphicon-chevron-right"></span>
      <% end %>
    </td><% end %>
      <% if user_signed_in? && current_user.email == 'st118173@ait.asia' %>
          <td><%= link_to  program, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" do %>Delete<span class="glyphicon glyphicon-chevron-right"></span>
                <% end %></td><% end %>
       </div>
  </div>
  <!-- /.row --><hr>
  <% end %>

  <!-- Pagination -->
  <div class="row text-center">
    <div class="col-lg-12">
      <ul class="pagination">
        <li>
          <!--<a href="#">&laquo;</a>-->
          <%= will_paginate @programs, renderer: BootstrapPagination::Rails,:previous_label => 'Previous', :next_label => 'Next' %>

        </li>

      </ul>
    </div>
  </div>

  <!-- /.row -->

  <hr>

  <!-- Footer -->
  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright &copy; Your Website 2014</p>
      </div>
    </div>
    <!-- /.row -->
  </footer>

</div>

</span>



<style>

  /*!
   * Start Bootstrap - 1 Col Portfolio (http://startbootstrap.com/)
   * Copyright 2013-2016 Start Bootstrap
   * Licensed under MIT (https://github.com/BlackrockDigital/startbootstrap/blob/gh-pages/LICENSE)
   */

  body {
    padding-top: 70px; /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
  }

  footer {
    margin: 50px 0;
  }

  table {
    border-spacing: 0;
    border-collapse: collapse;
  }
  td,
  th {
    padding: 0;
  }
  /*.btn.btn-success.hover{*/
    /*color: green;*/
  /*}*/
  /*!*! Source: https://github.com/h5bp/html5-boilerplate/blob/master/src/css/main.css *!*/

  /*.btn-info, .label-info, .alert-info {*/
    /*background-color: #FFF;*/
    /*border-color: #FFF;*/
    /*color: #01B0D1;*/
    /*float: left;*/
  /*}*/
  /*.btn-warning, .label-warning, .alert-warning {*/
    /*background-color: #e67e22;*/
    /*border-color: #e67e22;*/
    /*float: right;*/
    /*margin: -5.5%;*/
  /*}*/
  .btn-success:hover, .btn-success:focus {
    background-color: green;
    color: white;
    border-color: #c0392b;
  }
  .btn-danger:hover, .btn-danger:focus {
      background-color: red;
      color: white;
      border-color: #c0392b;
    }
  .btn-warning:hover, .btn-warning:focus {
    background-color: orange;
    color: white;
    border-color: #c0392b;
  }
  .btn-default:hover, .btn-default:focus {
    background-color: black;
    color: white;
    border-color: #c0392b;
  }
  .btn-info:hover, .btn-info:focus {
    background-color: green;
    color: white;
    border-color: #c0392b;
  }
  #btnSearch1,
  #btnSearch2,
  #btnSearch3,
  #btnSearch4{
    display: inline-block;
    vertical-align: top;
  }
  #btnSearch,
  #btnClear{
    display: inline-block;
    vertical-align: top;
  }

</style>
<style>
  #myImg {
    border-radius: 5px;
    cursor: pointer;
    transition: 0.3s;
  }

  #myImg:hover {opacity: 0.7;}

  /* The Modal (background) */
  .modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.9); /* Black w/ opacity */
  }

  /* Modal Content (image) */
  .modal-content {
    margin: auto;
    display: block;
    width: 80%;
    max-width: 700px;
  }

  /* Caption of Modal Image */
  #caption {
    margin: auto;
    display: block;
    width: 80%;
    max-width: 700px;
    text-align: center;
    color: #ccc;
    padding: 10px 0;
    height: 150px;
  }

  /* Add Animation */
  .modal-content, #caption {
    -webkit-animation-name: zoom;
    -webkit-animation-duration: 0.6s;
    animation-name: zoom;
    animation-duration: 0.6s;
  }

  @-webkit-keyframes zoom {
    from {-webkit-transform:scale(0)}
    to {-webkit-transform:scale(1)}
  }

  @keyframes zoom {
    from {transform:scale(0)}
    to {transform:scale(1)}
  }

  /* The Close Button */
  .close {
    position: absolute;
    top: 20px;
    right: 2%;
    color: greenyellow;
    font-size: 40px;
    font-weight: bold;
    transition: 0.3s;
  }

  .close:hover,
  .close:focus {
    color: #bbb;
    text-decoration: none;
    cursor: pointer;
  }

  /* 100% Image Width on Smaller Screens */
  @media only screen and (max-width: 700px){
    .modal-content {
      width: 100%;
    }
  }
</style>

app/views/programs/new.html.erb
<h1>New Event</h1>

<%= render 'form', program: @program %>

<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event name:</strong>
  <%= @program.Event_Name %>
</p>
<p>
  <strong>Event Details:</strong>
  <%= @program.event_details %>
</p>
<%= image_tag @program.photo.url(:medium) %>
<h3>Comments</h3>

<%= render @program.comts %>





<p><%= render 'comts/form' %></p>

<%= button_to( "Donate", new_reg_path, :method => :get, :class => 'btn btn-primary' )%>
<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', programs_path %>