config/routes.rb
Rails.application.routes.draw do
  resources :memberdetails do
    collection do
      get :download
    end
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :emails
  get 'ps/ps4'

  get 'ps/ps5'

  authenticated :user do

      root 'userpersnaldets#new'

    end
get 'home/home'
  get 'memberdetails/download'
  root 'home#home'
  resources :mdos
  resources :maa_addresses
  resources :regs
  resources :userpersnaldets
  captcha_route


  #root 'messages#index'
  resources :messages, only: [:create, :destroy, :index, :new]
  resources :programs do
    resources :comts

  end

  #resources :media_contents, only: [:create]

  delete 'delete_media', to: "media_contents#delete_media"
  delete 'delete_all', to: 'media_contents#delete_all'
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'usersinfo/userlist'
 #root 'programs#index'
  authenticated :user do
    #root 'programs#index'
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end
   #root 'courses#index'
  get 'courses/show'
  resources :courses do
    member do
      get 'upload', to: 'courses#upload'
      patch 'upload', to: 'courses#do_upload'
      get 'resume_upload', to: 'courses#resume_upload'
      patch 'update_status', to: 'courses#update_status'
      get 'reset_upload', to: 'courses#reset_upload'
    end
  end

  match ':controller(/:action(/:id))', :via => [:get,:patch,:post]
  get 'usersinfo/User'

  get 'usersinfo/uerlist'

  get 'usersinfo/userstat'

  #get 'usersinfo/show' => 'usersinfo/userlist'


  #root 'usersinfo#userstat'
  resources :usersinfo
  resources :project


  #root 'usersinfo#userlist'
  #get 'usersinfo/ban'
  #get 'usersinfo/unban'
  post "/regs/:id" => "regs#show"
  post "/hook" => "regs#hook"
  post "/mdos/:id" => "mdos#show"
  post "/hook" => "mdos#hook"
  get "myprofile" => "application#profile", :as => :myprofile

  get 'project/home'
 #root 'project#home'
  #root 'regs#index'
 #root 'mdos#index'

  #root 'userpersnaldets#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/mdo.rb
require 'csv'

class Mdo < ApplicationRecord
  #belongs_to :user
  has_one :card

  accepts_nested_attributes_for :card
  #validates  :full_name, :company, :email, :telephone, presence: true
  #validates_presence_of :amount

  serialize :notification_params, Hash
  def paypalurl(return_path)
    values = {
        business: "ait@test.com",
        cmd: "_xclick",
        upload: 1,
        return: "#{Rails.application.secrets.app_host}#{return_path}",
        invoice: id,
        amount: amount.to_d,
        item_name: "Donation",
        item_number: id,
        quantity: '1',
        notify_url: "#{Rails.application.secrets.app_host}/hook"
          }
          "#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" + values.to_query
        end

  def payment_method
    if card.nil? then "paypal"; else "card"; end
  end
  def self.to_csv(options = {})
    desired_columns = ["id", "amount", "full_name", "company",'email','telephone','status','transcation_id','purchased_at']
    CSV.generate(options) do |csv|
      csv << desired_columns
      all.each do |donate|
        csv << donate.attributes.values_at(*desired_columns)
      end
    end
  end

end

app/controllers/mdos_controller.rb
class MdosController < ApplicationController

  before_action :set_mdo, only: [:show, :edit, :update, :destroy]
  before_filter :check_role ,except: :index
  def check_role
    if user_signed_in? && current_user.role_id ==nil
      redirect_to new_reg_path

    end
  end
  # GET /Donations

  def index
    @count = Mdo.count
    #@mdo = Mdo.all
    #@mdos = Mdo.all
    @mdos = Mdo.all
    @mdo = Mdo.new
    @donations = Mdo.order(:id)
    respond_to do |format|
      format.html
      format.csv { send_data @donations.to_csv }
      format.xls
    end


  end

  # GET /Donations/1
  def show
    # if params[:action] == "index" && params[:controller] == "mdos"
    #   redirect_back(fallback_location: fallback_location)
    # end

    @mdos = Mdo.all

  end

  # GET /Donations/new
  def new

    #@user_type = params[:user_type]
    @mdo = Mdo.new
    @mdo.build_card
    @ack = CardTransaction.all
    # @course = Course.find_by id: params["course_id"]

  end


  # POST /Donations
  def create

    @mdo = Mdo.new(mdo_params)


      @mdo.card.ip_address = request.remote_ip until present?



    if @mdo.save
      #redirect_to @mdo.paypal_url(mdo_path(@mdo))
      case params[:payment]
        when "paypal"
          redirect_to @mdo.paypalurl(mdo_path(@mdo))
        when "card"
          if @mdo.card.donate
            redirect_to mdo_path(@mdo), notice: @mdo.card.card_transaction.message
          else
            redirect_to mdo_path(@mdo), alert: @mdo.card.card_transaction.message
          end
    else
      render :new
    end
    end

    end



  protect_from_forgery except: [:hook]
  def hook
    params.permit! # Permit all Paypal input params
    status = params[:payment_status]
    if status == "Completed"
      @mdo = Mdo.find params[:invoice]
      @mdo.update_attributes notification_params: params, status: status, transaction_id: params[:txn_id], purchased_at: Time.now
    end
    render nothing: true
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_mdo
    @mdo = Mdo.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def mdo_params

      params.fetch(:mdo,Hash.new).permit(:amount, :full_name, :company, :email, :telephone,
                                         card_attributes: [
                                             :first_name, :last_name, :card_type, :card_number,
                                             :card_verification, :card_expires_on])

  # params.require(:mdo).permit(:amount, :full_name, :company, :email, :telephone,
  #                             card_attributes: [
  #                                 :first_name, :last_name, :card_type, :card_number,
  #                                 :card_verification, :card_expires_on])
end

end

app/helpers/mdos_helper.rb
module MdosHelper
end

app/views/mdos/edit.html.erb
<h1>Editing Mdo</h1>

<%= render 'form', mdo: @mdo %>

<%= link_to 'Show', @mdo %> |
<%= link_to 'Back', mdos_path %>

app/views/mdos/index.html.erb
<script>
  $(document).ready(function () {

    $('.star').on('click', function () {
      $(this).toggleClass('star-checked');
    });

    $('.ckbox label').on('click', function () {
      $(this).parents('tr').toggleClass('selected');
    });

    $('.btn-filter').on('click', function () {
      var $target = $(this).data('target');
      if ($target != 'all') {
        $('.table tr').css('display', 'none');
        $('.table tr[data-status="' + $target + '"]').fadeIn('slow');
      } else {
        $('.table tr').css('display', 'none').fadeIn('slow');
      }
    });

  });
</script>
<style>
  #str1 {
    border: 1px solid #dddddd;
    border-radius: 5px;
    position: relative;
  }


  #str2{
    width: auto;
    height: 100%;
    overflow-x:hidden;
    padding-bottom: 82px;
    padding-top: 15px;
    /*text-align: center;*/

  }
</style>
<p id="notice"><%= notice %></p>



  <div class="row" align="center">

    <div id="str1" style="width: 16cm;height: 14cm;"; align="center">

    <div id="str2" class="wrapper container" style="height: 14.7cm;width: 16cm;border: double" align="left">
<% i = 1 %>
      <% count = 1 %>
      <div class="btn-group" align="center" style=" display:block;margin-left: -50%">
        <button type="button" class="btn btn-warning btn-filter" data-target="pagado" style="position: fixed;">Show Details</button>
        <button type="button" class="btn btn-danger btn-filter" data-target="pendiente"style="position: fixed; margin-left: 9%">Hide Details</button><br><br>
        <!--<button type="button" class="btn btn-danger btn-filter" data-target="cancelado">Cancelado</button>-->
        <%# @mdos.each do |mdo| %>
          <%# count +=1 %>
        <%# end %>
        <h5 style="position: fixed;margin-left: 30%  ">Total Donations are <%= @count %></h5><br><br><br>

      </div>

<% @mdos.each do |mdo| %>
          <%# if mdo.card.card_transaction.params["Ack"] == 'Success' %>
<div class="container" >
  <div class="row" align="left">

    <section class="content" style="width: 15cm;float: left">
      <h1>Donation-<%=i %></h1>
      <div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="pull-left">

            </div>
            <div class="table-container">
              <table class="table table-filter">
                <tbody>
                <tr data-status="pagado">



                  <td>
                    <div class="media">
                      <a href="" class="pull-left">
                        <%= image_tag('pp.png',width: '5cm',class: "media-photo") %> Donated by:
                      </a>
                      <div class="media-body">
                        <span class="media-meta pull-right">Feb 13, 2016</span>

                        <p class="title">Name:</p>
                        <%= mdo.full_name %>

                        <p class="title">Amount: </p>
                        <%= mdo.amount %>


                        <p class="title">Address: </p>
                        <%= mdo.company %>
                        </p>
                          <p>
                        <p class="title">Email: </p>
                        <%= mdo.email %>
                        </p>
                          <p>
                        <p class="title">Telephone: </p>
                        <%= mdo.telephone %>

                        </p>
                      </div>
                    </div>
                  </td>
                </tr>

                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="content-footer">
          <p>
            Payment © - Date: <%=mdo.created_at.strftime("%d %b. %Y")%> Time: <%= mdo.created_at.strftime("%I:%M %p")%><br>
            Powered By <a href="https://www.paypal.com" target="_blank">Paypal</a>
          </p>
        </div>
      </div>
    </section>

  </div>
</div>
<br>

<% i += 1 %>

          <% end %>
<%# end %>

    </div>

      <%= link_to 'New Donation ?', new_mdo_path, class: "btn btn-primary btn-lg btn-block" , style: "color: white;background: gray;" %>

      </p>

      <%= button_to "Export To Excel ?", mdos_path(format: "xls"),method: :get, id: 'triangle-right' %>
      <%= button_to "Export To CSV ?", mdos_path(format: "csv"),method: :get,id: 'triangle-left' %>
</div></div>
<!--<h5 style="position: absolute;  margin-top: -36%;margin-left: 37%">Total Donations are <%= count %></h5><br>-->
<p>



  <style>
    #triangle-right {

      font-size: x-large;
      border-top: 100px solid transparent;
      border-left: 150px solid green;
      border-bottom: 90px solid transparent;
      background: transparent;
      font-weight: bold;
      color: red;
      margin-left: 100%;
      margin-top: -80%;
      border-width: inherit;

    }
    #triangle-right:hover {

      width: 0;
      height: 0;
      border-top: 100px solid transparent;
      border-left: 150px solid #4CAF50;
      border-bottom: 90px solid transparent;
      background: transparent;
      margin-top: -95%;
      margin-right: -28%;
    }
    #triangle-left {

      font-size: x-large;
      border-top: 100px solid transparent;
      border-right: 150px solid slategrey;
      border-bottom: 90px solid transparent;
      background: transparent;
      font-weight: bold;
      color: red;
      margin-left: -132%;
      margin-top: -4%;
      border-width: inherit;
    }
    #triangle-left:hover {

      width: 0;
      height: 0;
      border-top: 100px solid transparent;
      border-right: 150px solid #4CAF50;
      border-bottom: 90px solid transparent;
      background: transparent;
      margin-top: -18%;
      margin-right: -4.3%;

    }

  </style>
</p>
<script>
  $("#triangle-left").hover(function(){
    $('#triangle-right').css('visibility', 'hidden');
  }, function(){
    $('#triangle-right').css('visibility', 'visible');
  });

  $("#triangle-right").hover(function(){
    $('#triangle-left').css('visibility', 'hidden');
  }, function(){
    $('#triangle-left').css('visibility', 'visible');
  });

</script>

app/views/mdos/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table style="background-color: snow;background: border-box">
      <Row style="background: green">
        <Cell style = 'color: white'><Data ss:Type="String">ID</Data></Cell>
        <Cell style = 'color: white'><Data ss:Type="String">Amount</Data></Cell>
        <Cell style = 'color: white'><Data ss:Type="String">Full Name</Data></Cell>
        <Cell style = 'color: white'><Data ss:Type="String">Company/Address</Data></Cell>
        <Cell style = 'color: white'><Data ss:Type="String">Email</Data></Cell>
        <Cell style = 'color: white'><Data ss:Type="String">Telephone</Data></Cell>
        <Cell style = 'color: white'><Data ss:Type="String">Status</Data></Cell>
        <Cell style = 'color: white'><Data ss:Type="String">Transaction id</Data></Cell>
        <Cell style = 'color: white'><Data ss:Type="String">Donated on</Data></Cell>
      </Row>
      <% @mdos.each do |mdo| %>
          <Row>
            <Cell><Data ss:Type="Number"><%= mdo.id %></Data></Cell>
            <Cell><Data ss:Type="String"><%= mdo.amount %></Data></Cell>
            <Cell><Data ss:Type="String"><%= mdo.full_name %></Data></Cell>
            <Cell><Data ss:Type="String"><%= mdo.company %></Data></Cell>
            <Cell><Data ss:Type="String"><%= mdo.email %></Data></Cell>
            <Cell><Data ss:Type="String"><%= mdo.telephone %></Data></Cell>
            <Cell><Data ss:Type="String"><%= mdo.status %></Data></Cell>
            <Cell><Data ss:Type="String"><%= mdo.transaction_id %></Data></Cell>
            <Cell><Data ss:Type="datetime"><%= mdo.purchased_at %></Data></Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/mdos/new.html.erb
<h1 align="center">Enter Donation Details</h1>
<h2  align="center">If you want to Donate Education materials then <%= link_to 'Click here',new_course_path,style: 'color:#3498db;background:transparent' %> else continue </h2>

<%= render 'form', mdo: @mdo %>

<%= link_to 'Back', mdos_path %>

app/views/mdos/show.html.erb
<ul><ul><ul><table >
<tr><td align="center"><ul><%= image_tag("print.png", :width=>130, :height=>130, :onclick=>"PrintDiv();", :class=>'btn') %></ul></td></tr>
  <td>
    <div class="divprint" id="divToPrint">

      <section id="course-content">
        <section id="ruby">
          <section class="detailed-syllabus">
            <div class="wrapper-inside">


              <link rel="stylesheet" type="text/css" media="print" href="">
            </div>
            <div class="columns clearfix">
              <div class="left" style="padding-left:100px;">


                <table align="center" style="border: solid;border-color: green;background-color: white">
                  <% if notice %>
                      <p id="notice" style="background-color: lightgreen;padding: 5px;">
                        <%= notice %>
                      </p>
                  <% end %>
                  <% if alert %>
                      <p id="alert" style="background-color: lightpink;padding: 5px;">
                        <%= alert %>
                      </p>
                  <% end %>
                  <tr><td align="center"  colspan="3"><%= image_tag("let.jpg", :width=>530, :height=>200)%></td></tr>

                  <tr> <td align="center" style="color: green" colspan="3"><h4>Donation invoice</h4></td></tr>
                  <td> <strong>Price:</strong></td>
                  <td>  <%= @mdo.amount  %></td>

                  </tr>
                  <tr>
                    <td>  <strong>Full name:</strong></td>
                    <td>  <%= @mdo.full_name %></td>
                  </tr>
                  <tr>
                    <td>  <strong>Company:</strong></td>
                    <td>  <%= @mdo.company %></td>
                  </tr>
                  <tr>
                    <td>  <strong>Email:</strong></td>
                    <td>  <%= @mdo.email %></td>
                  </tr>
                  <tr>
                    <td> <strong>Telephone:</strong></td>
                    <td>  <%= @mdo.telephone %></td>
                  </tr>
                  <tr>
                    <td>  <strong>Payment date:</strong></td>
                    <td>  <%= @mdo.purchased_at %></td>
                  </tr>
                  <tr>
                    <td>  <strong>Payment method:</strong></td>
                    <td> <%= @mdo.payment_method.capitalize %></td>
                  </tr>
                  <% if @mdo.payment_method == "paypal" %>
                      <tr>
                        <td>  <strong>Payment status:</strong></td>
                        <td>  <%= @mdo.status %></td>
                      </tr>
                      <tr>
                        <td>  <strong>Paypal Transaction Identifier:</strong></td>
                        <td>  <%= @mdo.transaction_id %></td>
                      </tr>
                  <% else %>
                      <tr>
                        <td>  <strong>Transaction Identifier:</strong></td>
                        <td>  <%= @mdo.card.card_transaction.params["transaction_id"] %></td>
                      </tr>
                      <tr>
                        <td>  <strong>Payment Status:</strong></td>
                        <td>  <%= @mdo.card.card_transaction.params["Ack"] %></td>
                      </tr>

                  <% end %>
                </table>
              </div>



            </div>

          </section>
        </section>
      </section>
    </div>
    <script type="text/javascript">
      function PrintDiv() {
        var divToPrint = document.getElementById('divToPrint');
        var popupWin = window.open('', '_blank', 'width=300,height=300');
        popupWin.document.open();
        popupWin.document.write('<html><body onload="window.print()">' + divToPrint.innerHTML + '</html>');
        popupWin.document.close();

      }
    </script></td>

</table></ul></ul></ul>
<div class="row">
  <% if user_signed_in?  %>
<% if @mdo.card.card_transaction.params["Ack"] == 'Success' %>
    <%= button_to "Back", programs_path,method: :get,class: "btn btn-large btn-success"   %>
<% else %>
    <%= button_to "Back to payment", new_mdo_path,method: :get,class: "btn btn-danger"   %>


<% end %>
</div>
  <% else %>
      <% if @mdo.card.card_transaction.params["Ack"] == 'Success' %>
          <%= button_to "Back", root_path,method: :get,class: "btn btn-large btn-success"   %>
      <% else %>
          <%= button_to "Back to payment", new_mdo_path,method: :get,class: "btn btn-danger"   %>


      <% end %>
  <% end %>